apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: amrmahmoud377/auth-paas
      context: auth
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: amrmahmoud377/email-paas
      context: email
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: amrmahmoud377/database-engine-paas
      context: database-engine
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: amrmahmoud377/database-order-paas
      context: databsae-order
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: amrmahmoud377/database-management-paas
      context: database-management
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
#    - image: amrmahmoud377/client-paas
#      context: client
#      docker:
#        dockerfile: Dockerfile
#      sync:
#        manual:
#          - src: '**/*.js'
#            dest: .