apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngrok-ingress-controller-role-binding
subjects:
  - kind: ServiceAccount
    name: default  # Replace with the actual service account name used by Ngrok
    namespace: ngrok-ingress-controller  # Replace with the namespace where Ngrok Ingress Controller is deployed
roleRef:
  kind: ClusterRole
  name: nginx-ingress-role  # Replace with the name of a ClusterRole that grants necessary permissions to list ingresses
  apiGroup: rbac.authorization.k8s.io
